### ISSUE TITLE
Crash on startup in Linux related to #153

### ISSUE THREAD

**Issue by dpendolino** [Kethku/neovide#180]
I'm running Arch Linux with the latest `rustup` stable toolchain and neovim v0.4.3. The error happens on the latest nightly toolchain as well.

Neovide crashes with the attached stack trace from the AUR and when using `cargo run` on master.

I ran a `git bisect` and it seems the crash starts happened at the following commit;

```
✦ ➜ git bisect good
#153 is the first bad commit
commit 0b301cb69007316e8588444ddd57d56a88b6ce1d
Author: Raffael Zica <1042414+SirJson@users.noreply.github.com>
Date:   Thu Feb 27 16:55:34 2020 +0100

    Shaper includes system symbol fonts into cache
    
    This should fix #153 on Windows but needs testing on Linux and macOS.

 src/renderer/caching_shaper.rs | 15 +++++++++++++++
 1 file changed, 15 insertions(+)
```

Stacktrace:
[stacktrace.txt](https://github.com/Kethku/neovide/files/4295138/stacktrace.txt)

**Comment by Kethku** [comment]
Fixed.

**Comment by dpendolino** [comment]
Same error on the latest master (c9b9b3eee8397150deca54dbbdfee853eaf5519d).
[stacktrace2.txt](https://github.com/Kethku/neovide/files/4303827/stacktrace2.txt)

**Comment by Kethku** [comment]
Ok it should actually be fixed now. Can you try again? Sorry for the struggles

**Comment by dpendolino** [comment]
No worries and thanks for all the effort!

Still crashing but now the windows pops up briefly and I have a different error:

```
$ RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/neovide`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0:     0x556029da3864 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x556029da3864 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x556029da3864 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x556029da3864 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x556029dc99bc - core::fmt::write::h393d55821fa8e2cb
                               at src/libcore/fmt/mod.rs:1025
   5:     0x556029da0517 - std::io::Write::write_fmt::hc6645302c23e4504
                               at src/libstd/io/mod.rs:1426
   6:     0x556029da5a0e - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x556029da5a0e - std::sys_common::backtrace::print::hc2635fd6c7743ade
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x556029da5a0e - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
                               at src/libstd/panicking.rs:193
   9:     0x556029da5701 - std::panicking::default_hook::h66e3afff11b02e47
                               at src/libstd/panicking.rs:210
  10:     0x556029da60eb - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
                               at src/libstd/panicking.rs:471
  11:     0x556029da5c9e - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x556029dc5d1e - core::panicking::panic_fmt::he794217b0df3f806
                               at src/libcore/panicking.rs:84
  13:     0x556029dc5c6a - core::panicking::panic::h104b3bcaeb5f1ff0
                               at src/libcore/panicking.rs:51
  14:     0x5560293e9032 - core::option::Option<T>::unwrap::hf11eb513fa7d43dc
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15
  15:     0x55602931865a - neovide::renderer::caching_shaper::CachingShaper::get_skia_font::h4f70f50ed3c9ab15
                               at src/renderer/caching_shaper.rs:189
  16:     0x556029318c57 - neovide::renderer::caching_shaper::CachingShaper::shape::h5504983b2195a264
                               at src/renderer/caching_shaper.rs:214
  17:     0x556029319166 - neovide::renderer::caching_shaper::CachingShaper::shape_cached::hc0f6952afe9c9225
                               at src/renderer/caching_shaper.rs:234
  18:     0x5560293690c8 - neovide::renderer::Renderer::draw_foreground::hb492aa15926eeec9
                               at src/renderer/mod.rs:97
  19:     0x556029369de5 - neovide::renderer::Renderer::draw::hee9de24d542ac628
                               at src/renderer/mod.rs:155
  20:     0x55602931ead9 - neovide::window::WindowWrapper::draw_frame::{{closure}}::h5047be50bc98c8be
                               at src/window.rs:274
  21:     0x55602935d78c - skulpin::renderer::renderer::Renderer::do_draw::haf32b9cb3d1d3818
                               at /home/dpendolino/.cargo/git/checkouts/skulpin-2e78d5d442751fde/3c87846/src/renderer/renderer.rs:409
  22:     0x55602935cc69 - skulpin::renderer::renderer::Renderer::draw::h9585f1ba006cc7b9
                               at /home/dpendolino/.cargo/git/checkouts/skulpin-2e78d5d442751fde/3c87846/src/renderer/renderer.rs:300
  23:     0x5560292c4253 - neovide::window::WindowWrapper::draw_frame::hcd500a54db5f0b84
                               at src/window.rs:271
  24:     0x5560292c48c7 - neovide::window::ui_loop::h90bb22428641f4b7
                               at src/window.rs:334
  25:     0x556029276311 - neovide::main::h4ecea022b68cece7
                               at src/main.rs:31
  26:     0x556029308570 - std::rt::lang_start::{{closure}}::hf51aa8f4ea25ce42
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  27:     0x556029da5b33 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
                               at src/libstd/rt.rs:52
  28:     0x556029da5b33 - std::panicking::try::do_call::h0630fe3da32a089b
                               at src/libstd/panicking.rs:292
  29:     0x556029dae01a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  30:     0x556029da6580 - std::panicking::try::hdfbe2fd873ac646c
                               at src/libstd/panicking.rs:270
  31:     0x556029da6580 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
                               at src/libstd/panic.rs:394
  32:     0x556029da6580 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
                               at src/libstd/rt.rs:51
  33:     0x556029308549 - std::rt::lang_start::h6a00d96480657865
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  34:     0x55602927634a - main
  35:     0x7f4611c10023 - __libc_start_main
  36:     0x55602924d34e - _start
  37:                0x0 - <unknown>
```

The process also never seems to exit.

**Comment by Kethku** [comment]
are you running from the release or building from master for the above error?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dpendolino** [comment]
Sorry , my bad for not specifying. The above trace was from the current master branch. 

I have also tried on the 0.5.0 tag and get this error instead:
```
 RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/neovide`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15:40
stack backtrace:
   0:     0x556040c1b9c4 - backtrace::backtrace::libunwind::trace::he25250f78ba1020d
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x556040c1b9c4 - backtrace::backtrace::trace_unsynchronized::hd7e25f35da233a1e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x556040c1b9c4 - std::sys_common::backtrace::_print_fmt::h5578a566a4c2ae4e
                               at src/libstd/sys_common/backtrace.rs:84
   3:     0x556040c1b9c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4f87054ec86e936
                               at src/libstd/sys_common/backtrace.rs:61
   4:     0x556040c41b1c - core::fmt::write::h393d55821fa8e2cb
                               at src/libcore/fmt/mod.rs:1025
   5:     0x556040c18677 - std::io::Write::write_fmt::hc6645302c23e4504
                               at src/libstd/io/mod.rs:1426
   6:     0x556040c1db6e - std::sys_common::backtrace::_print::he8a0a3ebec70e1d6
                               at src/libstd/sys_common/backtrace.rs:65
   7:     0x556040c1db6e - std::sys_common::backtrace::print::hc2635fd6c7743ade
                               at src/libstd/sys_common/backtrace.rs:50
   8:     0x556040c1db6e - std::panicking::default_hook::{{closure}}::h9849388798b72b2b
                               at src/libstd/panicking.rs:193
   9:     0x556040c1d861 - std::panicking::default_hook::h66e3afff11b02e47
                               at src/libstd/panicking.rs:210
  10:     0x556040c1e24b - std::panicking::rust_panic_with_hook::hf6d05969fcffff03
                               at src/libstd/panicking.rs:471
  11:     0x556040c1ddfe - rust_begin_unwind
                               at src/libstd/panicking.rs:375
  12:     0x556040c3de7e - core::panicking::panic_fmt::he794217b0df3f806
                               at src/libcore/panicking.rs:84
  13:     0x556040c3ddca - core::panicking::panic::h104b3bcaeb5f1ff0
                               at src/libcore/panicking.rs:51
  14:     0x55604026fa22 - core::option::Option<T>::unwrap::hf11eb513fa7d43dc
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libcore/macros/mod.rs:15
  15:     0x55604023303a - neovide::renderer::caching_shaper::CachingShaper::get_skia_font::hf85486747b31ca25
                               at src/renderer/caching_shaper.rs:175
  16:     0x556040233517 - neovide::renderer::caching_shaper::CachingShaper::shape::h943f606b4e4c1f04
                               at src/renderer/caching_shaper.rs:200
  17:     0x5560402339f6 - neovide::renderer::caching_shaper::CachingShaper::shape_cached::he963e47d6cb97826
                               at src/renderer/caching_shaper.rs:220
  18:     0x55604016a798 - neovide::renderer::Renderer::draw_foreground::h895ae6bb4a0f192a
                               at src/renderer/mod.rs:97
  19:     0x55604016b4b5 - neovide::renderer::Renderer::draw::ha6dbc8eeecaa4c93
                               at src/renderer/mod.rs:155
  20:     0x5560400d9c4b - neovide::window::WindowWrapper::draw_frame::{{closure}}::hef646911c6e04b0c
                               at src/window.rs:249
  21:     0x556040144c4c - skulpin::renderer::renderer::Renderer::do_draw::h313fc65f39882f27
                               at /home/dpendolino/.cargo/git/checkouts/skulpin-2e78d5d442751fde/9c62459/src/renderer/renderer.rs:409
  22:     0x556040144129 - skulpin::renderer::renderer::Renderer::draw::h5bbee638c13412aa
                               at /home/dpendolino/.cargo/git/checkouts/skulpin-2e78d5d442751fde/9c62459/src/renderer/renderer.rs:300
  23:     0x5560401b478d - neovide::window::WindowWrapper::draw_frame::h31a6606248939b25
                               at src/window.rs:246
  24:     0x5560401b4d8d - neovide::window::ui_loop::h6624d8c68d9347cf
                               at src/window.rs:304
  25:     0x55604023d541 - neovide::main::hebbacce28095f401
                               at src/main.rs:31
  26:     0x556040189b80 - std::rt::lang_start::{{closure}}::h5974723f4987a49e
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  27:     0x556040c1dc93 - std::rt::lang_start_internal::{{closure}}::h4aedff5d9863b36b
                               at src/libstd/rt.rs:52
  28:     0x556040c1dc93 - std::panicking::try::do_call::h0630fe3da32a089b
                               at src/libstd/panicking.rs:292
  29:     0x556040c2617a - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:78
  30:     0x556040c1e6e0 - std::panicking::try::hdfbe2fd873ac646c
                               at src/libstd/panicking.rs:270
  31:     0x556040c1e6e0 - std::panic::catch_unwind::hd7a9c10fa2bee1bc
                               at src/libstd/panic.rs:394
  32:     0x556040c1e6e0 - std::rt::lang_start_internal::hb8081e0e7e42ac0d
                               at src/libstd/rt.rs:51
  33:     0x556040189b59 - std::rt::lang_start::h76a60a04db8b47f8
                               at /rustc/f3e1a954d2ead4e2fc197c7da7d71e6c61bad196/src/libstd/rt.rs:67
  34:     0x55604023d57a - main
  35:     0x7f95f7a87023 - __libc_start_main
  36:     0x5560400d52fe - _start
  37:                0x0 - <unknown>
[xcb] Unknown sequence number while appending request
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
neovide: xcb_io.c:145: append_pending_request: Assertion `!xcb_xlib_unknown_seq_number' failed.
Aborted (core dumped)
```

**Comment by SirJson** [comment]
Mh so I looked into it and the first crash is probably fixed now and could have been avoided by declaring Unifont as a dependency on Linux. The master stack trace relates to #145 tho. 

I'm looking into reproducing this type of crash and see if I can work around it.

**Comment by Kethku** [comment]
I added some more error propagation to the font loading which might do a better job of catching the error

**Comment by Kethku** [comment]
@SirJson maybe we should embed Unifont? I know people are already complaining about the build size, but I figure it would just fix some of these issues...

**Comment by SirJson** [comment]
Yea I just saw that 20 minutes ago someone exactly implemented the workaround, and I was wondering why it didn't crash :grin:

So the issue with Unifont is the licence. As far as I know it is under GPL3 which would mean that if Unifont is embedded neovide also has to be GPL3. 

I think the better solution is to detect that the symbol font isn't there, tell the user that and give him the option to choose another symbol font instead.

Also now with the workaround in place I think a similar notice should be implemented for text fonts. Because right now if I build without embedded fonts, don't have Unifont on my system and set my guifont to "Tamzen" I just get a empty window without any error message.

**Comment by Kethku** [comment]
The struggle becomes how to notify the user. I suppose I can use error logging so that the message gets printed to the console, but that doesn't exactly work on windows machines where a console isn't necessarily visible

I seem to recall sdl having a messagebox system... I'll look into it.

**Comment by SirJson** [comment]
Weird, I also thought SDL had something like this but I can't find it in the Wiki. 

But I wouldn't worry about Windows too much here, a call to MessageBoxW is super easy. It's the other two platforms where SDL would really help.

**Comment by Kethku** [comment]
https://rust-sdl2.github.io/rust-sdl2/sdl2/messagebox/index.html

**Comment by Kethku** [comment]
Atm all errors are either logging messages or std out. What we are proposing here is a third category which is a messagebox error for when we don't think the editor will recover but need to show some text to the user that we are sure they would see. Maybe I could hook error logs and always show them via messagebox since they should be fatal in general?

**Comment by Kethku** [comment]
@dpendolino sorry to keep attempting. Can you try again? I fixed the next error you encountered.

**Comment by dpendolino** [comment]
@Kethku No worries! Latest master is building and running great, just a couple of warnings:

```
warning: unused variable: `command_error`
  --> src/bridge/mod.rs:95:16
   |
95 |     if let Err(command_error) = nvim.command("runtime! ginit.vim").await {
   |                ^^^^^^^^^^^^^ help: consider prefixing with an underscore: `_command_error`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: field is never read: `ignore_text_input`
  --> src/window.rs:52:5
   |
52 |     ignore_text_input: bool,
   |     ^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1m 35s
     Running `target/debug/neovide`
```

Thanks!
