### ISSUE TITLE
Incosistent font size with other neovim GUIs

### ISSUE THREAD

**Issue by kishikaisei** [Kethku/neovide#387]
So basically Neovide renders font smaller than nvim-qt, or goneovim:
![image](https://user-images.githubusercontent.com/1894123/96498915-fb6d7080-124c-11eb-8918-ba33faabb77b.png)
Goneovim, nvim-qt and Neovide respectively.

**Comment by felipec** [comment]
Just installed neovide and this is literally the first thing I noticed.

**Comment by Kethku** [comment]
Not sure why this would be happening given that we are delegating to skia to handle the end result font rendering and the font size is directly taken from the guifont variable.

**Comment by felipec** [comment]
The DPI setting? I am using 120, not 96.

**Comment by Kethku** [comment]
Possible, but not sure. I think I can see a font size difference on my machine as well. In the meantime, neovide declares a global neovide variable on startup, so you could look for that and conditionally set the font size in your config until we figure out whats going on

**Comment by Kethku** [comment]
I believe this was fixed by @last-partizan

**Comment by last-partizan** [comment]
It isn't fixed yet, but we're closer to fix than before, i'll take a look :)

![image](https://user-images.githubusercontent.com/301015/125034457-45c3a580-e099-11eb-8a3c-1cc3c808ee66.png)

**Comment by last-partizan** [comment]
Btw, we're assuming fonts are in "pixels", but maybe they're actually in "points"? That explains difference, we need to convert our scaling factor to account for this conversion.

**Comment by last-partizan** [comment]
Anyone interested please check `fix-scaling` branch.
