### ISSUE TITLE
Intercepts xkbmap rebindings when using Xorg keyboard layout

### ISSUE THREAD

**Issue by Exr0n** [Kethku/neovide#408]
I'm using `setxkbmap -option caps:ctrl-modifier` which should rebind caps lock to control. Other applications seem to receive the modified sequence okay but Neovide only gets the letter key (no control modifier).

Looks related to #151 (same issue, different symptoms? If you would like to consolidate discussion there, please lmk and close this :)

I'm using `neovide-git` on the AUR (`--version` says `0.6.0` but it should track master?), X11, and Arch 5.9.13. Please let me know if I can do anything to help!

**Comment by Kethku** [comment]
What layout of keyboard are you using? The issue you linked is related to keyboard layout handling.

**Comment by Kethku** [comment]
I wouldn't be surprised if this is an sdl2 limitation...

**Comment by Exr0n** [comment]
I'm using Dvorak via `xorg.conf`. Removing that line indeed fixes the issue.   Sorry, I didn't realize that this was the cause. If it's an SDL2 bug I guess it has to be reported upstream.

**Comment by Kethku** [comment]
I believe this will be solved by https://github.com/Kethku/neovide/issues/445 but I'm leaving it open because I want to circle back to it once we rebase. Until then consider this blocked on the upstream winit changes.

**Comment by Exr0n** [comment]
Solved by #445! Can't wait to start daily driving neovide :)

**Comment by Kethku** [comment]
@Exr0n out of curiosity, what issues remain for your use case?

**Comment by Exr0n** [comment]
> @Exr0n out of curiosity, what issues remain for your use case?

Nothing! Just spent a half hour configuring and I'm good to go :)

Although, I can't figure out how to change my cursor color. (not a big deal though)

I have added
```vimscript
highlight Cursor        guifg=black     guibg=#caca00
highlight iCursor       guifg=black     guibg=steelblue
```
to my config, but it doesn't seem to be doing anything. Any ideas?

**Comment by Kethku** [comment]
Honestly not sure. The cursor style is specified by neovim. We get a list of styles and then a list of cursor modes which reference the styles by id. Then the current mode is sent in an event which we handle by looking up the cursor mode and then the cursor style from that.

So I think it has something to do with your configured syntax highlighting, but I've never done anything beyond just set gruvbox and forget about it :P

**Comment by Exr0n** [comment]
Strange. Thanks for taking a look anyhow, and being on top of the GitHub issues! This is probably the most active project I've seen, truly a gem of open source. Cheers!
