### ISSUE TITLE
[MacOS Catalina] thread 'main' panicked at 'Failed to parse emoji font data: Parse'

### ISSUE THREAD

**Issue by mdudzinski** [Kethku/neovide#76]
This commit broke this ca24df79e690795d235099fd2d171a76b9cfe54a
Especially this lines https://github.com/Kethku/neovide/blob/b7368ac11035e034459ae5bb8873cf21e14293ea/src/renderer/caching_shaper.rs#L87-L89

Seems like this font is not supported on MacOS --> https://github.com/googlefonts/noto-emoji/issues/72

The simplest workaround is to comment out that three lines. In a long term, a different font should be used for MacOS builds.

Full trace:
```
   Finished dev [unoptimized + debuginfo] target(s) in 8.19s
     Running `target/debug/neovide`
thread 'main' panicked at 'Failed to parse emoji font data: Parse', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::ArgumentV1::show_usize
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
            at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16: neovide::renderer::caching_shaper::build_collection_by_font_name
             at src/renderer/caching_shaper.rs:88
  17: neovide::renderer::caching_shaper::FontSet::new
             at src/renderer/caching_shaper.rs:110
  18: neovide::renderer::caching_shaper::CachingShaper::new
             at src/renderer/caching_shaper.rs:149
  19: neovide::renderer::Renderer::new
             at src/renderer/mod.rs:30
  20: neovide::window::ui_loop
             at src/window.rs:33
  21: neovide::main
             at src/main.rs:23
  22: std::rt::lang_start::{{closure}}
  23: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  24: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  26: std::panicking::try
             at src/libstd/panicking.rs:265
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  29: std::rt::lang_start
  30: neovide::main
```

**Comment by heliostatic** [comment]
Also breaks on `10.14.6` with the same commit, https://github.com/Kethku/neovide/commit/ca24df79e690795d235099fd2d171a76b9cfe54a (unsurprisingly)

**Comment by Kethku** [comment]
You mean to tell me that fonts can be incompatible with OSs. Computers were a mistake...

Luckily I think macos has an emoji font which is always available, so I will add a conditional compilation to handle it on mac.

Sigh...

**Comment by Kethku** [comment]
Should be fixed.

**Comment by Kethku** [comment]
Please reopen if it is still a problem!

**Comment by sebnow** [comment]
Still doesn't work for me @ 71406ba6cb90322f40cd2385e99bad129f60b528. I thought it might be a typo with the case of the font name (It's "Apple C**O**lor Emoji" atm), but changing it didn't fix anything. Also trying "Apple Color Emoji Regular" didn't work.

![Screen Shot 2020-01-29 at 16 32 54](https://user-images.githubusercontent.com/8548/73370856-2675f580-42b5-11ea-8d1f-a0ad520eb0f9.png)

**Comment by Kethku** [comment]
My bad folks. Thanks for the PR should be fixed for real now.

**Comment by mdudzinski** [comment]
Wow, that was fast! Thanks guys, it works fine now
